"use client";
import Link from "next/link";
import { useTransition } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { setStaffActiveAction } from "../actions";
type Row={id:string;name:string;user:{name:string|null;email:string}|null;services:string[];isActive:boolean};
export function StaffManager({slug,staff}:{slug:string;staff:Row[]}){const[,start]=useTransition();return <div className="overflow-x-auto rounded-xl border border-border"><table className="w-full min-w-[760px] text-sm"><thead><tr className="border-b border-border text-left text-muted-foreground"><th className="p-4">Name</th><th className="p-4">Linked member</th><th className="p-4">Assigned services</th><th className="p-4">Status</th><th className="p-4">Actions</th></tr></thead><tbody>{staff.map(s=><tr key={s.id} className="border-b border-border last:border-0"><td className="p-4 font-medium">{s.name}</td><td className="p-4">{s.user?`${s.user.name??"Unnamed"} (${s.user.email})`:"Not linked"}</td><td className="p-4">{s.services.length?s.services.join(", "):"None"}</td><td className="p-4"><Badge variant={s.isActive?"accent":"outline"}>{s.isActive?"Active":"Archived"}</Badge></td><td className="p-4"><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" render={<Link href={`/app/${slug}/staff/${s.id}`} />}>Edit</Button><Button size="sm" variant="outline" render={<Link href={`/app/${slug}/staff/${s.id}/schedule`} />}>Schedule</Button><Button size="sm" variant="ghost" onClick={()=>start(async()=>{const r=await setStaffActiveAction(slug,s.id,!s.isActive);if("error"in r)toast.error(r.error);else{toast.success(s.isActive?"Staff archived":"Staff restored");window.location.reload();}})}>{s.isActive?"Archive":"Restore"}</Button></div></td></tr>)}</tbody></table></div>}
