import { afterEach, describe, expect, it, vi } from "vitest";
import { availabilityQuerySchema } from "@/features/public-booking/schemas";
import { groupBookingOptions } from "@/features/public-booking/group-options";
import { bookingHref, parseBookingParams } from "@/features/public-booking/booking-params";
import { buildIcs } from "@/features/public-booking/ics";
import { ACCENT_COLORS, accentStyle, resolveAccent } from "@/features/public-booking/accent-colors";
import { dateToString, formatLongDateTime, formatSlotLabel, stringToDate, zoneCityName } from "@/features/public-booking/time-display";
import { bookingErrorMessage } from "@/features/public-booking/messages";
import { getAppUrl } from "@/server/app-url";
afterEach(() => vi.unstubAllEnvs());
describe("public booking", () => {
 it("validates availability queries", () => { const base={slug:"northside-barbers",serviceId:"svc1",date:"2027-01-12"}; expect(availabilityQuerySchema.safeParse(base).success).toBe(true); expect(availabilityQuerySchema.safeParse({...base,staffId:"stf1",rescheduleToken:"a".repeat(32)}).success).toBe(true); for(const value of [{...base,date:"2027-02-30"},{...base,date:"2027-1-5"},{...base,slug:"Northside"},{...base,serviceId:""},{...base,staffId:""},{...base,rescheduleToken:"short"}]) expect(availabilityQuerySchema.safeParse(value).success).toBe(false); });
 it("groups services and staff in stable order", () => { const result=groupBookingOptions({services:[{id:"cut",name:"Cut",durationMinutes:45,priceCents:3500},{id:"beard",name:"Beard",durationMinutes:30,priceCents:2000},{id:"shave",name:"Shave",durationMinutes:15,priceCents:1000}],staff:[{id:"s1",name:"Ann",bio:null,photoUrl:null},{id:"s2",name:"Ben",bio:null,photoUrl:null}],links:[{serviceId:"cut",staffId:"s1"},{serviceId:"cut",staffId:"s2"},{serviceId:"beard",staffId:"s2"},{serviceId:"beard",staffId:"s9"},{serviceId:"shave",staffId:"s9"}]}); expect(result.services.map(s=>s.name)).toEqual(["Beard","Cut"]); expect(result.services[0]!.staff.map(s=>s.name)).toEqual(["Ben"]); expect(result.services[1]!.staff.map(s=>s.name)).toEqual(["Ann","Ben"]); });
 it("parses booking parameters and creates stable links", () => { const options={services:[{id:"svc-cut",staff:[{id:"stf-ann"},{id:"stf-ben"}]},{id:"svc-beard",staff:[{id:"stf-ben"}]}]}; const range={firstDate:"2027-01-11",lastDate:"2027-03-12"}; expect(parseBookingParams({},options,range).step).toBe("service"); expect(parseBookingParams({service:"nope"},options,range).step).toBe("service"); expect(parseBookingParams({service:"svc-cut"},options,range).step).toBe("staff"); expect(parseBookingParams({service:"svc-cut",staff:"any"},options,range)).toMatchObject({step:"time",staffId:"any"}); expect(parseBookingParams({service:"svc-cut",staff:"stf-zed"},options,range).step).toBe("staff"); expect(parseBookingParams({service:"svc-beard"},options,range)).toMatchObject({step:"time",staffId:"stf-ben"}); expect(parseBookingParams({service:"svc-cut",staff:"any",date:"2027-03-13"},options,range)).not.toHaveProperty("date"); expect(parseBookingParams({service:"svc-cut",staff:"any",date:"2027-01-12"},options,range)).toHaveProperty("date","2027-01-12"); expect(parseBookingParams({service:"svc-cut",staff:"any",date:"2027-01-12",time:"2027-01-12T16:00:00.000Z"},options,range).step).toBe("details"); expect(parseBookingParams({service:"svc-cut",staff:"any",date:"2027-01-12",time:"2027-01-12T10:00:00-06:00"},options,range)).toMatchObject({step:"time"}); expect(parseBookingParams({service:"svc-cut",staff:"any",date:"2027-01-12",time:["2027-01-12T16:00:00.000Z","bad"]},options,range).step).toBe("details"); expect(parseBookingParams({time:"2027-01-12T16:00:00.000Z"},options,range).step).toBe("service"); expect(bookingHref("northside-barbers",{service:"svc-cut",staff:"any",date:"2027-01-12"})).toBe("/book/northside-barbers?service=svc-cut&staff=any&date=2027-01-12"); expect(bookingHref("northside-barbers",{})).toBe("/book/northside-barbers"); });
 it("builds escaped, folded iCalendar data", () => { const value=buildIcs({bookingId:"bk1",startsAt:new Date("2027-01-12T16:00:00Z"),endsAt:new Date("2027-01-12T17:00:00Z"),now:new Date("2027-01-11T12:00:00Z"),summary:"Beard trim, hot towel; with Ann",description:"Line one\nLine two",url:"https://bookfleet.example"}); expect(value).toContain("UID:bk1@bookfleet"); expect(value).toContain("DTSTAMP:20270111T120000Z"); expect(value).toContain("DTSTART:20270112T160000Z"); expect(value).toContain("DTEND:20270112T170000Z"); expect(value).toContain("STATUS:CONFIRMED"); expect(value).toContain(String.raw`Beard trim\, hot towel\; with Ann`); expect(value).toContain("Line one\\nLine two"); expect(value.startsWith("BEGIN:VCALENDAR\r\nVERSION:2.0")).toBe(true); expect(value.endsWith("END:VEVENT\r\nEND:VCALENDAR\r\n")).toBe(true); expect(value.replace(/\r\n/g,"")).not.toContain("\n"); const long=buildIcs({bookingId:"bk1",startsAt:new Date("2027-01-12T16:00:00Z"),endsAt:new Date("2027-01-12T17:00:00Z"),now:new Date("2027-01-11T12:00:00Z"),summary:"Ã©".repeat(200),description:"",url:"https://example.test"}); expect(long.split("\r\n").every(line=>new TextEncoder().encode(line).length<=75)).toBe(true); });
 it("defines accessible accent colours", () => { expect(ACCENT_COLORS).toHaveLength(6); expect(new Set(ACCENT_COLORS.map(x=>x.key)).size).toBe(6); expect(new Set(ACCENT_COLORS.map(x=>x.hex)).size).toBe(6); expect(ACCENT_COLORS[0]!.key).toBe("pine"); const luminance=(hex:string)=>{const rgb=hex.slice(1).match(/../g)!.map(x=>parseInt(x,16)/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4);return .2126*rgb[0]!+.7152*rgb[1]!+.0722*rgb[2]!}; for(const c of ACCENT_COLORS){expect(1.05/(luminance(c.hex)+.05)).toBeGreaterThanOrEqual(4.5);const [r,g,b]=c.hex.slice(1).match(/../g)!.map(x=>parseInt(x,16)/255) as [number,number,number];const max=Math.max(r,g,b),min=Math.min(r,g,b),delta=max-min;let h=0;if(delta){if(max===r)h=60*(((g-b)/delta)%6);else if(max===g)h=60*((b-r)/delta+2);else h=60*((r-g)/delta+4)}if(h<0)h+=360;expect(h<250||h>330).toBe(true)} expect(resolveAccent("#a6323a").key).toBe("brick"); expect(resolveAccent(null).key).toBe("pine"); expect(resolveAccent("#123456").key).toBe("pine"); expect(Object.keys(accentStyle("#1F5F4F")).sort()).toEqual(["--primary","--primary-foreground","--ring"]); });
 it("formats times and local calendar dates", () => { const instant=new Date("2027-01-12T16:00:00Z"); expect(formatSlotLabel({instant,timeZone:"America/Chicago",anchorDate:"2027-01-12"})).toBe("10:00 AM"); expect(formatSlotLabel({instant,timeZone:"Europe/London",anchorDate:"2027-01-12"})).toBe("4:00 PM"); expect(formatSlotLabel({instant,timeZone:"Asia/Kolkata",anchorDate:"2027-01-12"})).toBe("9:30 PM"); expect(formatSlotLabel({instant:new Date("2027-01-13T03:30:00Z"),timeZone:"Asia/Kolkata",anchorDate:"2027-01-12"})).toBe("9:00 AM (Wed 13)"); expect(formatLongDateTime(instant,"America/Chicago")).toBe("Tue, Jan 12 at 10:00 AM"); expect(formatLongDateTime(instant,"Europe/London")).toBe("Tue, Jan 12 at 4:00 PM"); expect(zoneCityName("America/Chicago")).toBe("Chicago"); expect(zoneCityName("America/Argentina/Buenos_Aires")).toBe("Buenos Aires"); expect(zoneCityName("UTC")).toBe("UTC"); expect(dateToString(new Date(2027,0,5))).toBe("2027-01-05"); const d=stringToDate("2027-01-05"); expect([d.getFullYear(),d.getMonth(),d.getDate(),d.getHours()]).toEqual([2027,0,5,0]); });
 it("maps every booking error to its public message", () => { expect(bookingErrorMessage("SLOT_TAKEN")).toBe("That time was just taken. Please pick another time."); expect(bookingErrorMessage("PLAN_LIMIT_REACHED")).toBe("This business can't take new online bookings right now. Please contact them directly."); expect(bookingErrorMessage("SERVICE_NOT_FOUND")).toBe("That service isn't available any more."); expect(bookingErrorMessage("INVALID_INPUT")).toBe("Please check your details and try again."); expect(bookingErrorMessage("BOOKING_NOT_FOUND")).toBe("We couldn't find that booking."); expect(bookingErrorMessage("NOT_CONFIRMED")).toBe("This booking has already been cancelled or finished."); expect(bookingErrorMessage("ALREADY_STARTED")).toBe("This appointment has already started, so it can't be changed online. Please contact the business."); expect(bookingErrorMessage("UNKNOWN")).toBe("Something went wrong on our side. Please try again."); expect(bookingErrorMessage("PLAN_LIMIT_REACHED")).not.toMatch(/plan|limit|free|upgrade/i); });
 it("validates the app URL configuration", () => { vi.stubEnv("NEXT_PUBLIC_APP_URL","https://bookfleet.example/"); expect(getAppUrl()).toBe("https://bookfleet.example"); vi.stubEnv("NEXT_PUBLIC_APP_URL",""); vi.stubEnv("NODE_ENV","development"); expect(getAppUrl()).toBe("http://localhost:3000"); vi.stubEnv("NODE_ENV","production"); expect(()=>getAppUrl()).toThrow(); vi.stubEnv("NODE_ENV","development"); vi.stubEnv("NEXT_PUBLIC_APP_URL","not a url"); expect(()=>getAppUrl()).toThrow(); });
});

