/* eslint-disable react-hooks/set-state-in-effect */
"use client";
import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Calendar } from "@/components/ui/calendar";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { bookingHref } from "../booking-params";
import { dateToString, formatSlotLabel, stringToDate } from "../time-display";
export function TimePicker({ slug, serviceId, staffId, timezone, firstDate, lastDate, initialDate, rescheduleToken }: { slug: string; serviceId: string; staffId: string | null; timezone: string; firstDate: string; lastDate: string; initialDate: string; rescheduleToken?: string }) { const router = useRouter(); const [date, setDate] = useState(initialDate); const [slots, setSlots] = useState<string[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(false); const load = useCallback(async (selectedDate: string, signal?: AbortSignal) => { setLoading(true); setError(false); try { const params = new URLSearchParams({ slug, serviceId, date: selectedDate }); if (staffId) params.set("staffId", staffId); if (rescheduleToken) params.set("rescheduleToken", rescheduleToken); const response = await fetch(`/api/public/availability?${params}`, { cache: "no-store", signal }); if (!response.ok) throw new Error("Availability failed"); const data = await response.json() as { slots: { startsAt: string }[] }; setSlots(data.slots.map((item) => item.startsAt)); } catch (e) { if (!(e instanceof DOMException && e.name === "AbortError")) setError(true); } finally { if (!signal?.aborted) setLoading(false); } }, [slug, serviceId, staffId, rescheduleToken]); useEffect(() => { const controller = new AbortController(); void load(date, controller.signal); return () => controller.abort(); }, [date, load]); const chooseDate = (next: Date | undefined) => { if (!next) return; const value = dateToString(next); setDate(value); window.history.replaceState(null, "", `${bookingHref(slug, { service: serviceId, staff: staffId ?? "any", date: value })}${rescheduleToken ? `&rescheduleToken=${rescheduleToken}` : ""}`); }; return <div className="grid gap-6 md:grid-cols-[auto_1fr]"><Calendar mode="single" selected={stringToDate(date)} onSelect={chooseDate} disabled={(day) => { const value = dateToString(day); return value < firstDate || value > lastDate; }} /><section><p aria-live="polite" className="mb-3 text-sm text-muted-foreground">{loading ? "Loading available times…" : `${slots.length} times available on ${date}`}</p>{loading ? <div className="grid grid-cols-2 gap-2">{Array.from({ length: 8 }, (_, i) => <Skeleton key={i} className="h-10" />)}</div> : error ? <div role="alert">Could not load times. <Button variant="outline" onClick={() => void load(date)}>Retry</Button></div> : slots.length === 0 ? <p>No times on this day. Try another day.</p> : <div className="grid grid-cols-2 gap-2">{slots.map((iso) => <Button key={iso} variant="outline" onClick={() => router.push(bookingHref(slug, { service: serviceId, staff: staffId ?? "any", date, time: iso }))}>{formatSlotLabel({ instant: new Date(iso), timeZone: timezone, anchorDate: date })}</Button>)}</div>}</section></div>; }
